import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import { Divider } from '@mui/material'
import Link from 'next/link'
import {  FacebookTwoTone, Instagram, Twitter } from '@mui/icons-material'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <main>
<Navbar/>    
<Hero/>

<section className='min-h-[70dvh]'>
  <h2 className='font-bold text-3xl text-center text-dark-red my-20 '>Why Us? </h2>
  <div className='grid grid-cols-3 text-dark-blue w-[80%] mx-auto text-center leading-[2rem] gap-4' >
    <div className='shadow p-3'>
    <Image src='/images/favorite.png' width={100} height={100} alt="trust" className='mx-auto'/>

      <h3 className='font-bold text-lg text-dark-red text-center my-3'>We are the best</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur vel quaerat reiciendis modi illum quibusdam eum reprehenderit error beatae esse.</p>
    </div>
    <div className='shadow p-3'>
      <Image src='/images/trust.png' width={100} height={100} alt="trust" className='mx-auto'/>
      <h3 className='font-bold text-lg text-dark-red center my-3'>Trust</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur vel quaerat reiciendis modi illum quibusdam eum reprehenderit error beatae esse.</p>
    </div>
    <div className='shadow p-3'>
    <Image src='/images/first.png' width={100} height={100} alt="trust" className='mx-auto'/>
      <h3 className='font-bold text-lg text-dark-red text-center my-3'>Customer First</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur vel quaerat reiciendis modi illum quibusdam eum reprehenderit error beatae esse.</p>
    </div>

  </div>
</section>
   </main> 

<Divider className='w-[80%] mx-auto'/>
<section className='grid grid-cols-2 text-center w-1/2 mx-auto py-20 gap-10'>
  <div>

  <h3 className='font-bold text-lg text-dark-red text-center  uppercase '>Rent A property</h3>
  <p className='text-dark-blue my-4'>Post an Ads for a room you want to rent and make people with an apartment find you</p>
  <button className='bg-milk text-dark-blue py-2 px-4 rounded hover:shadow-md '>Avertise For Free</button>
  </div>

  <div>

<h3 className='font-bold text-lg text-dark-red text-center  uppercase '>Rent A property</h3>
<p className='text-dark-blue my-4'>Post an Ads for a room you want to rent and make people with an apartment find you</p>
<button className='bg-milk text-dark-blue py-2 px-4 rounded hover:shadow-md '>Avertise For Free</button>
</div>

</section>
<Divider className='w-[80%] mx-auto'/>

<section className='min-h-[50dvh] bg-dark-blue grid place-content-center' >

  <div className=' text-white flex justify-between w-[80dvw] mx-auto flex-wrap'>

  <div>
    <h3 className='text-3xl font-bold my-4'>About Re-Room</h3>
    <ul className='text-[.8rem] grid gap-2'>
      <li><Link href="" className='hover:underline'>About Us</Link></li>

      <li><Link href="" className='hover:underline'>  Why Use Re-Room</Link></li>
      <li><Link href="" className='hover:underline'>  How  Re-Room works</Link></li>
      <li><Link href="" className='hover:underline'>  Terms and Conditions</Link></li>
      <li><Link href="" className='hover:underline'>  Privacy Policy</Link></li>



    </ul>
  </div>
  <div>
    <h3 className='text-3xl font-bold my-4'>Our Services</h3>
    <ul className='text-[.8rem] grid gap-2'>
      <li><Link href="" className='hover:underline'>Advertise a Room</Link></li>

      <li><Link href="" className='hover:underline'>  Post a room</Link></li>
      <li><Link href="" className='hover:underline'>  Adveritise a Property</Link></li>
      <li><Link href="" className='hover:underline'>  Find Roomates</Link></li>
      <li><Link href="" className='hover:underline'>  Privacy Policy</Link></li>



    </ul>
  </div>


  <div>
    <h3 className='text-3xl font-bold my-4'>Contact Us</h3>
    <ul className='text-[.8rem] grid gap-2'>
      <li><Link href="" className='hover:underline'>Send Us  a mail</Link></li>

      <li><Link href="" className='hover:underline'>  Call us:01673829383</Link></li>
      <li><Link href="" className='hover:underline'>  How  Re-Room works</Link></li>
  
      <li>Follow us<Link href="" className='hover:underline'><FacebookTwoTone/> </Link> <Link href=''><Instagram/></Link><Link href=''> <Twitter/></Link></li>



    </ul>
  </div>



  <div>
    <h3 className='text-3xl font-bold my-4'>Account</h3>
    <ul className='text-[.8rem] grid gap-2'>
      <li><Link href="" className='hover:underline'>Create Account</Link></li>

      <li><Link href="" className='hover:underline'>  Login</Link></li>
      <li><Link href="" className='hover:underline'>  Account Recovery</Link></li>




    </ul>
  </div>
  </div>
</section>

    </>
  )
}
